### ISSUE TITLE
New logo Sextant

### ISSUE THREAD

**Issue by reallinfo** [giusepe/Sextant#11]
Hello, I designed a logo for Sextant. I combined a navigasyon and sextant icon. I designed a logo in 2 different styles. If you like any of these, I will send you a pr. 

![sextant](https://user-images.githubusercontent.com/36298335/40027901-d292ba32-57e4-11e8-9a98-ae7d58935ea1.jpg)

e.g. In the readme file it will look like this;

![1](https://user-images.githubusercontent.com/36298335/40027937-fc7ce8fe-57e4-11e8-9980-0c75725b61e7.png)

**Comment by giusepe** [comment]
WoW!
Just wooow! :)

I believe the first one will fit better on a nuget package.

And thank you so much for doing this.

**Comment by reallinfo** [comment]
You're welcome. I sent a pr. Please check it. 

https://github.com/giusepe/Sextant/pull/18
