### ISSUE TITLE
Push Page weird behavior

### ISSUE THREAD

**Issue by LoneStar1994** [giusepe/Sextant#29]
Hi, I already ran the original  code and I happen to  have a very weird issue.

Whenever I reach the "Second Modal" and press the "Push Page" button nothing happnes. However, when I do "pop modals" I happen to come across with the pages that I actually "Pushed" on the Second Modal... which can be described like this:

At frist:
Home Page -> First Modal -> Second modal (PUSH)

After push:
Home Page -> Pushed Page from second modal -> First Modal -> Second Modal

After poping pushed page:
Home Page -> First Modal -> Second Modal

I dont know if I made my self clear, any ways, I'm tyring to figure out what is going on but I happen to hae the exact same issue when working along with my own solution...

Thank you!

**Comment by RLittlesII** [comment]
@LoneStar1994 After looking at your flow.  This is working as I would expect it.

Sextant (like Xamarin Forms) has two distinct navigation stacks managed by the NavigationService.  You can push and pop to these stacks independent of each other.

What your experiencing is a scenario where the developer has allowed the user to push multiple pages onto the modal stack.  The user is then allowed to push a navigation page onto the stack.  The page being pushed onto the Page Navigation stack, doesn't give it screen precedence (i.e. it doesn't display over the top of the modal pages).  It is hidden behind the modal stack until the modal stack is cleared.  This is why when you push the page, then pop the other two pages you are on the "Red Page".

This is useful for moments when you might want to push a modal, navigate away from the underlying screen, pop the modal so the user doesn't see two navigations.

The onus is on the developer to manage the navigation stack for the user.

Does this answer your question?

**Comment by LoneStar1994** [comment]
Alright! I'll try it out, thank you a lot.

**Comment by LoneStar1994** [comment]
I've been trying around with lots of different combinations but can't make it work... I belive that there is something behind the "IObservable" rutine that I'm missing.  How do you implement this?:
(Sorry for being so annoying)
After that all you have to do is call one of the methods inside your ViewModels:

        /// <summary>
        /// Pops the <see cref="IPageViewModel"/> off the stack.
        /// </summary>
        /// <param name="animate">if set to <c>true</c> [animate].</param>
        /// <returns></returns>
        IObservable<Unit> PopModal(bool animate = true);

        /// <summary>
        /// Pops the <see cref="IPageViewModel"/> off the stack.
        /// </summary>
        /// <param name="animate">if set to <c>true</c> [animate].</param>
        /// <returns></returns>
        IObservable<Unit> PopPage(bool animate = true);

        /// <summary>
        /// Pushes the <see cref="IPageViewModel"/> onto the stack.
        /// </summary>
        /// <param name="modal">The modal.</param>
        /// <param name="contract">The contract.</param>
        /// <returns></returns>
        IObservable<Unit> PushModal(IPageViewModel modal, string contract = null);

        /// <summary>
        /// Pushes the <see cref="IPageViewModel"/> onto the stack.
        /// </summary>
        /// <param name="page">The page.</param>
        /// <param name="contract">The contract.</param>
        /// <param name="resetStack">if set to <c>true</c> [reset stack].</param>
        /// <param name="animate">if set to <c>true</c> [animate].</param>
        /// <returns></returns>
        IObservable<Unit> PushPage(IPageViewModel page, string contract = null, bool resetStack = false, bool animate = true);

**Comment by RLittlesII** [comment]
Cannot make what work exactly?  

- What is the use case that you are solving that you are unable to accomplish? 
- What is your expected result?

The code you referenced is either the [NavigationView](https://github.com/giusepe/Sextant/blob/master/Sextant/Navigation/NavigationView.cs) or the [ViewStackService](https://github.com/giusepe/Sextant/blob/master/Sextant/Navigation/ViewStackService.cs) both of which are sourced in this project, so you can view the implementations.

**Comment by LoneStar1994** [comment]
1.- I'm trying to do what you suggested, to clear the stacklayout. And I thought that using the "IObservable" implementation I could make it work, cus I see you have a "ResetStack" option, which I belive is what I need... some how...

2.- I have two modal pages. a "Login" page and a "Home" page... my idea is to PushModal from Login to Home and then push pages from homes... but everytime I pushpages from home they wont appear but next to the "LoginPage". So I expect to "flush" the stackview to prevent Loggin page to appear when pressing "back button" and also poping all pages to the second modal page...

**Comment by RLittlesII** [comment]
If you could provide a sample repository to show what you are attempting that would be great.

I will go back to there are two navigation stacks that are not aware of each other.

I think the problem (this is without having looked at any code sample) is that your expectation of *how* modals work in Xamarin.Forms.  More specifically as the [Xamarin Forms Modal Navigation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/modal) docs state, modals must be explicitly dismissed from the screen.

If you push something onto the modal stack, it must be dismissed by the user (Popped from the modal stack) before elements on the Page Navigation stack are seen.  Unless I am wrong, you cannot push a Page to the Page stack from a modal page.

So I believe in the example you just provided, you would need to Pop the login page from the Modal Stack and then Push a Navigation Page to the PageStack.  You are attempting to start navigation from a modal page which I am not sure is possible.  And if it is in Xamarin Forms, then it would be a limitation of this library that you cannot currently do this.

when you set `Current.MainPage = new NavigationPage(new Page());` in your App.xaml.cs of a Xamarin.Forms application, you aren't pushing a modal, you are setting a page that is wrapped in a navigation page to MainPage of the app.

Does that make sense?

Have you tried your same example in Xamarin.Forms just by using the `INavigation` interface?  I'd be interested if a Modal Page allows you to go directly into Hierarchical Navigation. 

Additional reading
- [INavigation](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.inavigation?view=xamarin-forms)
- [Xamarin Forms Navigation](http://blog.adamkemp.com/2014/09/navigation-in-xamarinforms_2.html)

**Comment by RLittlesII** [comment]
[Modal Page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/modal)
[Hierarchical Navigation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical)

A modal is generally a Page that is put in front of the user that demands attention.  Think of a JavaScript pop up that comes out and forces the user to interact.  The actual page you are on still functions in the background, but you can't interact with it until you dismiss the modal in front of you.  It isn't apples to apples, but that is basically what is going on.  When you push a modal, you can push as many as you want onto a stack specifically for Modal Pages.  All the Hierarchical pages still exist behind all the modals, but until the modals are dismissed, the *user* cannot interact with them.  I explicitly call out the user interaction because the developer can still push and pop pages from the Hierarchical stack while modals are presented to the user.

So I am going to assume you have figured out how to make work what you needed?

**Comment by LoneStar1994** [comment]
Oh!! I Get It!! 

So you use this "Modal" as a substitute for the "Master Detail" where "Master" is the Pop Modal" and the "Page" is just the subordinated of the root page... So that is why you cannot push pages from a modal! because modal is an auxiliar page but not ment to act as a "Main Page wich pushes subpages"...

If that is so then I think I'm getting the deal here.

**Comment by RLittlesII** [comment]
Awesome.  Glad you're headed down the right path.  I am going to close this issue.  If you have anything else, feel free to reopen, or create a new issue.
